LOG_FOLDER = "logs/"
GAMMA_API_URL = "https://gamma-api.polymarket.com"
POLYMARKET_HOST = "https://clob.polymarket.com"
POLYMARKET_WS_MARKET_URL = "wss://ws-subscriptions-clob.polymarket.com/ws/market"
POLYMARKET_WS_USER_URL = "wss://ws-subscriptions-clob.polymarket.com/ws/user"
CHAIN_ID = 137
REQUEST_TIMEOUT = 5
PROFIT_MARGIN = 0.04
TRADING_BPS_THRESHOLD = 50
MAX_TRADING_BPS_THRESHOLD = 100
MARKET_SESSION_SECONDS = 900
TIMEZONE = "US/Eastern"
MAX_TRADES = 30
MAX_INVENTORY = 1
MIN_DELAY_BETWEEN_TRADES_SECONDS = 1
PLACE_OPPOSITE_ORDER = True  # Hedge orders
